### ISSUE TITLE
Missing png.c file

### ISSUE THREAD

**Issue by MrMaaoui** [JonFreer/COLMAP_OpenGL_Renderer#1]
Hello,

I'm trying to use this solution to align data to the neural rendering in the wild paper, however, compiling the project keeps returning an _undefined reference to_ every method declared in png.h that suggests the implementation of the methods are missing, upon closer inspection, I noticed that the png.c file is missing.

Is it possible to provide me with the png.c file? or am I doing something wrong?

I'm using Ubunto as my OS, VSCode as my IDE with g++5 and c++11 and the bild task include -lglut, -lGLU and -lGL flags.

Thank you in advance.

**Comment by JonFreer** [comment]
Hi,

The project uses http://www.libpng.org/pub/png/libpng.html to handle png. You will have to build it separately for your os. I have mostly rewrote this project in python, I will work to have it pushed in the next couple of days. Let me know if you have any other questions.

Jon

**Comment by MrMaaoui** [comment]
Thank you for the fast reply, I will dowload and build it on my os.
Also, I will be looking forward to the python implimentation.

**Comment by JonFreer** [comment]
Sorry this is later than I said but here is the python implementation. https://github.com/JonFreer/python_colmap_rerenderer

I have only tested it a little but it seems to work. It is a lot slower than the c++ implementation. If speed is critical you can change the density which will reduce the number of points rendered. 

I found https://github.com/colmap/colmap/tree/dev/scripts/python, mainly visualize_model.py, which used open3D to render the point cloud. This might be faster than my python only method.

Hope this helps.

**Comment by MrMaaoui** [comment]
Thank you for the update, 
I'll make sure to update you on the python_colmap_rerenderer repo if I encounter any issues.
